// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Web_Lab2.Migrations
{
    [DbContext(typeof(DataModelContext))]
    [Migration("20241127154357_sqlite.local_migration_415")]
    partial class sqlitelocal_migration_415
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Web_Lab2.Entities.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailableForAdoption")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShelterId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ShelterId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 3,
                            Breed = "Golden Retriever",
                            IsAvailableForAdoption = true,
                            Name = "Buddy",
                            ShelterId = 1,
                            Weight = 30.5
                        },
                        new
                        {
                            Id = 2,
                            Age = 2,
                            Breed = "Beagle",
                            IsAvailableForAdoption = true,
                            Name = "Charlie",
                            ShelterId = 1,
                            Weight = 20.0
                        },
                        new
                        {
                            Id = 3,
                            Age = 4,
                            Breed = "Bulldog",
                            IsAvailableForAdoption = false,
                            Name = "Max",
                            ShelterId = 2,
                            Weight = 25.0
                        });
                });

            modelBuilder.Entity("Web_Lab2.Entities.DogShelter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DogShelters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Shelter St.",
                            ContactNumber = "123-456-7890",
                            Name = "Shelter One"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Shelter Ave.",
                            ContactNumber = "987-654-3210",
                            Name = "Shelter Two"
                        });
                });

            modelBuilder.Entity("Web_Lab2.Entities.Dog", b =>
                {
                    b.HasOne("Web_Lab2.Entities.DogShelter", "DogShelter")
                        .WithMany("Dogs")
                        .HasForeignKey("ShelterId");

                    b.Navigation("DogShelter");
                });

            modelBuilder.Entity("Web_Lab2.Entities.DogShelter", b =>
                {
                    b.Navigation("Dogs");
                });
#pragma warning restore 612, 618
        }
    }
}
